---
title: "15_fishies_results"
author: "Caroline McKeon"
date: "15/08/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 10, fig.width = 16)
# set working directory
setwd("~/Library/CloudStorage/OneDrive-Personal/PhD/Fishies/fishies/2022_moriarty_kelly_mckeon_updates")

list<-c("ggplot2", "data.table", "reshape2", "arm","car", "DMwR", "Hmisc",
        "lme4", "plyr", "plotrix", "colorspace", "plot3D", "plot3D", "rgl","MuMIn",
        "mapplots", "class", "gridExtra", "ggmap", "tidyverse", "beepr", "raster", "ncdf4", "marmap", "rgdal", "foreign",
        "sf", "glmmTMB", "DHARMa", "sjPlot")

lapply(list, require, character.only=T)
#lapply(list, citation)

## create "not in" operator
'%nin%' = Negate('%in%')

## pairs function
upper.panel<-function(x, y){
  points(x,y, pch=21, col=c("grey"), cex = 0.5)
  r <- round(cor(x, y), digits=2)
  txt <- paste0("R = ", r)
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  text(0.8, 0.9, txt, cex =0.7)
}
```

```{r plotting themes}
# blank theme
set_theme(
  base = theme_classic(),
  axis.title.size = 2,
  axis.textsize = 1.2,
  legend.size = 2,
  legend.title.size = 2,
  geom.label.size = 3,
  plot.margin = margin(3, 5, 1, 5, "pt")
)

## text editing
get_wraper <- function(width) {
  function(x) {
    lapply(strwrap(x, width = width, simplify = FALSE), paste, collapse="\n")}}
## colour palett
cb_pal <- c("#01665e", "#5ab4ac","#c7eae5", "#d8b365", 
            "#8c510a")
r <- c("total.area", "range.size", "effective.mesh.size", "prop.landscape", "mean.shape.index", "perimeter.area.frac.dim")

```

## read in data and models
```{r}
## read in data ------------
setwd("~/Library/CloudStorage/OneDrive-Personal/PhD/Fishies/fishies/2022_moriarty_kelly_mckeon_updates")

mydata <- readRDS("Data_modeldf_abundance.rds")

#cont_null <- readRDS("")
cont_full <- readRDS("cwm_models/PC1_2way.rds")
cont_full5 <- readRDS("cwm_5/PC1_2way.rds")
```


```{r eval=FALSE, include=FALSE}
summary(cont_full)
summary(cont_full5)
```


```{r}
check <- broom.mixed::tidy(cont_full, effects = "fixed", conf.int = TRUE, conf.level = 0.95)
check5 <- broom.mixed::tidy(cont_full5, effects = "fixed", conf.int = TRUE, conf.level = 0.95)
```

```{r}
x <- cont_full[["fit"]][["par"]]
```


```{r}
check <- check[-1,]
check5 <- check5[-1,]
#check <-check[2:32,]
```


## table of model results for plotting
```{r}
# sum <- list()
# for(i in r) {
# sum[[i]] <- as.data.frame(summary(m_metric_clim_hf[[i]][["hf"]][[1]][["Sol"]])[["statistics"]]);
# sum[[i]] <- setDT(sum[[i]], keep.rownames = TRUE)[]
# sum[[i]]$ci <- sum[[i]]$SD*qnorm(.95)
# sum[[i]] <- sum[[i]][2:6,] 
# sum[[i]]$rn <- c("MAT", "MAT_var", "MAP", "MAP_var", "HF")
# sum[[i]]$rn <- factor(sum[[i]]$rn,
#                       levels = c("MAP", "MAP_var", "MAT", "MAT_var", "HF"))
# }


sum <- list()
for(i in r) {
sum[[i]] <- as.data.frame(summary(m_metric_clim_hf_vel[[i]][["hf"]][[1]])$solutions);
sum[[i]] <- setDT(sum[[i]], keep.rownames = TRUE)[]
sum[[i]] <- sum[[i]][c(2:7),]
sum[[i]]$rn <- c( "Vel","HF", "MAP", "MAT", "MAP_var","MAT_var")
sum[[i]]$rn <- factor(sum[[i]]$rn,
                     levels = c( "MAP_var","MAT_var","MAP", "MAT","Vel",  "HF"))
}


## woaw....
#check <- broom.mixed::tidy(m_metric_clim_hf_vel[["total.area"]][["hf"]][[1]], effects = "fixed", conf.int = TRUE, conf.level = 0.95)

```

```{r}
par(mfrow=c(3,3))
for (i in names(Filter(is.numeric, abundance))) {
  hist(abundance[,i], breaks = 1000, main = paste(i))
  gc()
}
```


## plot effect sizes

```{r}

ggplot(check,  aes(term, estimate, colour = term)) + 
      geom_hline(yintercept= 0, alpha = 0.8) +
  geom_line() +
  geom_pointrange(data = check,
                    aes(term, estimate, colour = term, ymin= conf.low, ymax= conf.high), 
                    position = position_dodge(0.5), size = 1.5) +
  ylim(-0.1, 0.1) 

ggplot(check5,  aes(term, estimate, colour = term)) + 
      geom_hline(yintercept= 0, alpha = 0.8) +
  geom_line() +
  geom_pointrange(data = check5,
                    aes(term, estimate, colour = term, ymin= conf.low, ymax= conf.high), 
                    position = position_dodge(0.5), size = 1.5) +
  ylim(-0.1, 0.1) 
  
    # theme(axis.line = element_line(colour = 'black', size = 1.5), 
    #       axis.title.x = element_blank(),
    #       axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
    #        plot.title = element_text(hjust = 0.5, size = 20)) 
    # 
  # scale_x_discrete(labels = get_wraper(10)) +
  # labs(colour = "Climate and HF", y = paste("Effect Size", n$V1[n$V2 ==i], sep = " ")) +
  # scale_color_viridis(discrete = TRUE) +
  #   ylim(-0.8, 0.8) 

```

```{r}
plot_model(cont_full, type = "int")
```


```{r}
autoplot(pc, data = b, colour = cl[b$feeding.mode], loadings = TRUE,
         loadings.label = TRUE, loadings.colour = "black", loadings.label.size = 4, 
         loadings.label.colour = "black")
```



```{r}
sum <- list()
for(i in r) {
sum[[i]] <- as.data.frame(summary(m_metric_clim_hf_vel[[i]][["hf"]][[1]])$solutions);
sum[[i]] <- setDT(sum[[i]], keep.rownames = TRUE)[]
sum[[i]] <- sum[[i]][c(2:22),]
sum[[i]]$main <- sum[[i]]$rn
sum[[i]]$main[grep(":", sum[[i]]$rn)] <- "interaction"
sum[[i]]$main[sum[[i]]$pMCMC <= 0.05 & sum[[i]]$main =="interaction"] <- "sig interaction"
sum[[i]]$main <- factor(sum[[i]]$main,
                     levels = c("map_mean", "map_var_mean", "mat_mean", "mat_var_mean","vel_mean", "hf_mean","sig interaction", "interaction"))

}
```

```{r fig.width=15, fig.height=19}
par(mfrow = c(6,1), mar=c(4.5,4.5,2,2), col="black", col.main = "black", col.lab = "black")

p <- list()

for(i in r){
  
p[[i]] <-  ggplot(sum[[i]],  aes(rn, post.mean, colour = main)) + 
      geom_hline(yintercept= 0, alpha = 0.8) +
  geom_line() +
  geom_pointrange(data = sum[[i]],
                    aes(rn, post.mean, colour = main, ymin= `l-95% CI`, ymax= `u-95% CI`), 
                    position = position_dodge(0.5), size = 1.5) +
    scale_color_manual(values = c("map_mean" = "#440154FF",
                                  "map_var_mean" = "#414487FF",
                                  "mat_mean" = "#2A788EFF",
                                  "mat_var_mean" = "#22A884FF",
                                  "vel_mean" =  "#7AD151FF", 
                                  "hf_mean" = "#FDE725FF", 
                                  "sig interaction" = "#7E7E7E",
                                  "interaction" = "#C1C1C1")) +


    theme(axis.line = element_line(colour = 'black', size = 1.5), 
          axis.title.x = element_blank(),
          axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
           plot.title = element_text(hjust = 0.5, size = 20)) +
    
  scale_x_discrete(labels = get_wraper(10)) +
  labs(colour = "interaction", y = paste("Effect Size", n$V1[n$V2 ==i], sep = " ")) +
    ylim(-1.2, 0.8) }

for(i in r){
  p[[i]] <- p[[i]] 
}

p[[1]] <- p[[1]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank()) 
p[[2]] <- p[[2]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank()) 
p[[3]] <- p[[3]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank()) 
p[[4]] <- p[[4]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank())

p[[5]] <- p[[5]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank())  
p[[6]] <- p[[6]] + theme(axis.text.x = element_blank(), axis.title.x = element_blank())  


resp <-ggarrange(p[[1]],p[[2]],p[[3]],p[[4]],p[[5]],p[[6]], labels = c("A", "B", "C", "D", "E", "F"), nrow = 3, ncol = 2, common.legend = TRUE, legend = "bottom")
# annotate_figure(resp, top = text_grob("Effects of climate and human footprint on range metrics", #color = "black", 
#                                       face = "bold", size = 20)
resp

```


## pairs plots for collinearity
```{r fig.width=10, fig.height=10}
colfunc <- colorRampPalette(c("#A715AD","white", "#FFB000"))


# cols <- as.character(c(1:66))
# cols[] <- "black"
# ## get correlation matrix
# dta.r = abs(cor(rat_[, which(names(rat_) %in% c("total.area", "range.size", "effective.mesh.size",
#                                       "mean.shape.index", "prop.landscape",
#                                       "perimeter.area.frac.dim", 
#                                       "mean", "mat_mean", "mat_var_mean", 
#                                       "map_mean", "map_var_mean"))])) 
# # get colors for these correlations
# dta.col <- dmat.color(dta.r, colors = colfunc(100), byrank = NULL, breaks = 100) 
# 
# cpairs(rat_[, which(names(rat_) %in% c("total.area", "range.size", "effective.mesh.size",
#                                       "mean.shape.index", "prop.landscape",
#                                       "perimeter.area.frac.dim", 
#                                       "mean", "mat_mean", "mat_var_mean", 
#                                       "map_mean", "map_var_mean"))], 
#        panel.colors=dta.col, gap=0.5,lower.panel = NULL)



upper.panel<-function(x, y){
        r <- round(cor(x, y), digits=2)
       # points(x,y, pch=21, col = metrics$mat_var_col, cex = 0.5)
        points(x,y, pch=21, col=c("grey"), cex = 0.5)
       # points(x,y, pch=21, col=colfunc(100)[r], cex = 0.5)
        txt <- paste0("R = ", r)
       # text(0.8, 0.9, txt, cex = 6* abs(cor(x, y)))
        usr <- par("usr"); on.exit(par(usr))
        par(usr = c(0, 1, 0, 1))
        text(0.6, 0.9, txt, cex =1.8)
}

#m <- drop_na(metrics)
m <- metrics[which(names(metrics) %nin% "Geographic range fractality")]
# pairs(rat_[, which(names(rat_) %in% c("total.area", "range.size", "effective.mesh.size",
#                                       "mean.shape.index", "prop.landscape",
#                                       "perimeter.area.frac.dim", 
#                                       "mean", "mat_mean", "mat_var_mean", 
#                                       "map_mean", "map_var_mean"))],
#       lower.panel = NULL, upper.panel = upper.panel)

# pairs(m[, which(names(m) %in% c("Occupied area", "Geographic range size", "Patch size distribution", "Geographic range filling", "Patch shape complexity", "Geographic range fractality"),)],
#       lower.panel = NULL, upper.panel = upper.panel)

pairs(m[, which(names(m) %in% c("Occupied area", "Geographic range size", "Patch size distribution", "Geographic range filling", "Patch shape complexity"),)],
      lower.panel = NULL, upper.panel = upper.panel)

pairs(m[, which(names(m) %in% c("hf_mean", "vel_mean", "mat_mean", "mat_var_mean", 
                                      "map_mean", "map_var_mean"))],
      lower.panel = NULL, upper.panel = upper.panel)

                                      
```

## visualise collinearity
```{r}
par(mfrow = c(1,3), pch = 20, cex = 1)

rbPal <- colorRampPalette(c('red','blue'))
rbPal <- colorRampPalette(v <- viridis(400, alpha = 1, begin = 0, end = 1, direction = 1, option = "D"))

metrics$mean_col <- rbPal(820)[as.numeric(cut(metrics$hf_mean,breaks = 820))]
metrics$mat_col <- rbPal(820)[as.numeric(cut(metrics$mat_mean,breaks = 820))]
metrics$t.a_col <- rbPal(820)[as.numeric(cut(metrics$`Occupied area`, breaks = 820))]

plot(metrics$`Occupied area` ~ metrics$mat_mean, col = metrics$mean_col)
plot(metrics$`Occupied area` ~ metrics$hf_mean, col = metrics$mat_col)
plot(metrics$mat_mean ~ metrics$hf_mean, col = metrics$t.a_col)
```



## plot r2s
```{r eval=FALSE, fig.height=6, fig.width=8, include=FALSE}
r2$model <- factor(r2$model, levels = c("null","hf", "clim", "clim_hf", "vel_clim", "vel_hf_clim"))
short <- r2[r2$r == "total.area",]

 ggplot(short,  aes(model, mode_r2_mar, colour = model)) + 
  geom_pointrange(data = short,
                    aes(model, mode_r2_mar, colour = model, ymin= `lower_r2_mar`, ymax= `upper_r2_mar`), 
                    position = position_dodge(width = 0.5), size = 2) +
     geom_pointrange(data = short,
                    aes(model, mean_r2_cond, colour = model, ymin= `lower_r2_cond`, ymax= `upper_r2_cond`),
                    position = position_dodge(width = 0.5), size = 2, shape = 1) +
  
    theme(axis.line = element_line(colour = 'black', size = 1.5), 
          axis.title.x = element_blank(),
          axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
           plot.title = element_text(hjust = 0.5, size = 20)) +
  labs(colour = "Model", title = paste(i), y = "R2") +
  scale_color_viridis(discrete = TRUE) +
    ylim(-0.01, 1) 

```


```{r}
# show_col(viridis_pal(option = "D", direction = 1)(5))
# dput(viridis_pal(option = "D", direction = 1)(5))

full_pal <-c("#FA9E3BFF", "#ED7953FF","#D8576BFF", "#BD3786FF","#7301A8FF",  "#47039FFF")


```

##plot conditional only
```{r}
r2 <- merge(n, r2, by.x = "V2", by.y = "r")
names(r2) <- c("r_old", "r", "mean_r2_mar", "mode_r2_mar", "lower_r2_mar", "upper_r2_mar", 
              "mean_r2_cond", "mode_r2_cond", "lower_r2_cond", "upper_r2_cond", "model")
r2$model <- factor(r2$model, levels = c("null","hf", "clim", "clim_hf", "vel_clim", "vel_hf_clim"))
r2$r <- factor(r2$r, levels = c("Occupied area", "Geographic range size", "Patch size distribution", "Geographic range filling", "Patch shape complexity", "Geographic range fractality"))
r2 <- r2[r2$r %nin% c("Patch shape complexity", "Geographic range fractality"),]
 ggplot(r2,  aes(r, mode_r2_mar, colour = model)) + 
     geom_pointrange(data = r2,
                    aes(r, mean_r2_cond, colour = model, ymin= `lower_r2_cond`, ymax= `upper_r2_cond`),
                    position = position_dodge(width = 0.5), size = 2) +
  
    theme(axis.line = element_line(colour = 'black', size = 1.5), 
          axis.title.x = element_blank(),
          axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +#, plot.title = element_text(hjust = 0.5, size = 20)) +
  labs(colour = "Model", y = "R2") +
  scale_color_manual(values=paste(full_pal)) +
  #scale_color_viridis(discrete = TRUE) +
    ylim(-0.01, 0.75) 
```




#FDBA00 - yellow
#A302B7 - purple
#02AFA8 - turquoise

```{r fig.width=20, fig.height=10}
#r2 <- merge(n, r2, by.x = "V2", by.y = "r")
names(r2) <- c("r_old", "r", "mean_r2_mar", "mode_r2_mar", "lower_r2_mar", "upper_r2_mar", 
              "mean_r2_cond", "mode_r2_cond", "lower_r2_cond", "upper_r2_cond", "model")
r2$model <- factor(r2$model, levels = c("null","hf", "clim", "clim_hf", "vel_clim", "vel_hf_clim"))
r2$r <- factor(r2$r, levels = c("Occupied area", "Geographic range size", "Patch size distribution", "Geographic range filling", "Patch shape complexity", "Geographic range fractality"))
 ggplot(r2,  aes(r, mode_r2_mar, colour = model)) + 
  geom_pointrange(data = r2,
                    aes(r, mean_r2_mar, colour = model, ymin= `lower_r2_mar`, ymax= `upper_r2_mar`), 
                    position = position_dodge(width = 0.5), size = 2) +
     geom_pointrange(data = r2,
                    aes(r, mean_r2_cond, colour = model, ymin= `lower_r2_cond`, ymax= `upper_r2_cond`),
                    position = position_dodge(width = 0.5), size = 2, shape = 1) +
  
    theme(axis.line = element_line(colour = 'black', size = 1.5), 
          axis.title.x = element_blank(),
          axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +#, plot.title = element_text(hjust = 0.5, size = 20)) +
  labs(colour = "Model", y = "R2") +
  scale_color_manual(values=paste(full_pal)) +
  #scale_color_viridis(discrete = TRUE) +
    ylim(-0.01, 0.75) 
```





```{r fig.width=16, fig.height=10}
r2$r <- factor(r2$r, levels = c("Occupied area", "Geographic range size", "Patch size distribution", "Geographic range filling", "Patch shape complexity", "Geographic range fractality"))
r2$model <- factor(r2$model, levels = c("null","hf", "clim", "clim_hf", "vel_clim", "vel_hf_clim"))
ggplot(r2,  aes(model, mode_r2_mar, colour = r)) + 
  geom_pointrange(data = r2,
                    aes(model, mean_r2_mar, colour = r, ymin= `lower_r2_mar`, ymax= `upper_r2_mar`), 
                    position = position_dodge(width = 0.5), size = 2) +
     geom_pointrange(data = r2,
                    aes(model, mean_r2_cond, colour = r, ymin= `lower_r2_cond`, ymax= `upper_r2_cond`),
                    position = position_dodge(width = 0.5), size = 2, shape = 1) +
  
    theme(axis.line = element_line(colour = 'black', size = 1.5), 
          axis.title.x = element_blank(),
          axis.text.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0))) +
  labs(colour = "Model", y = "R2") +
  scale_color_manual(values=paste(full_pal)) +
  #scale_color_viridis(discrete = TRUE) +
    ylim(-0.01, 0.75) 
```
















