---
title: "maps"
author: "Caroline McKeon"
date: "2023-06-29"
output:
  word_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sjPlot)
library(sp)
library(sf)
library(rnaturalearth)
library(raster)
library(viridis)
library(fasterize)
library(marmap)
# blank theme
set_theme(
  base = theme_classic(),
  axis.title.size = 2,
  axis.textsize = 1.2,
  legend.size = 2,
  legend.title.size = 2,
  geom.label.size = 3,
  plot.margin = margin(3, 5, 1, 5, "pt")
)
pal <- colorRampPalette(c('#0C276C', '#3B9088', '#EEFF00', '#ffffff'))

knitr::opts_chunk$set(fig.width=30, fig.height=20) 
```


```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
Europe <- world[which(world$continent == "Europe"),]

e <- Europe$geometry
e = st_as_sf(e)
e <- st_transform(e,"+proj=laea +lat_0=53 +lon_0=9 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs ")
```


```{r, fig.width= 20, fig.height=20}
sp_co <- readRDS("~/Library/CloudStorage/OneDrive-Personal/PhD/Fishies/fishies/2022_moriarty_kelly_mckeon_updates/Data_sp_co.rds")
s <- st_as_sf(sp_co, coords = c(1,2), crs = 4326)
sx <- st_transform(s, crs = crs(e))

par(bg = "transparent", mar = c(0,0,0,0))
plot(e, col='light gray', border='gray')
plot(sx, add = T, cex = 0.1)
plot(e, col='light gray', border='gray', add =T)
```

